"""Tests for scripts.export.legacy — registration, conversion and repositioning.

``reposition_supplemental_entries`` re-applies each supplemental's configured
``insertBeforeId`` / ``insertAfterId`` after ``reorder_manifest_entries`` (which sorts by the
previous manifest order) may have moved it. It also honours the per-page ``parliaments`` filter
so a page only repositions its own supplementals. Pure function operating on a list of dicts.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

import pytest

from scripts.export import legacy
from scripts.export.legacy import (
    SUPPLEMENTAL_LEGACY_ELECTIONS,
    apply_supplemental_legacy_elections,
)
from scripts.export.ordering import reposition_supplemental_entries


def _supplemental(sid: str) -> dict[str, Any]:
    """The configured supplemental with id ``sid`` (so anchors track the source of truth)."""
    return next(s for s in SUPPLEMENTAL_LEGACY_ELECTIONS if s["id"] == sid)


def _ids(entries: list[dict[str, Any]]) -> list[str]:
    return [e["id"] for e in entries]


class TestRepositionSupplementalEntries:
    def test_insert_before_anchor(self) -> None:
        # current-senate is configured to lead its class (insertBeforeId=2024-us-senate); a prior
        # reorder can push it to the end, so it must be pulled back in front of the anchor.
        anchor = _supplemental("current-senate")["insertBeforeId"]
        entries = [{"id": anchor}, {"id": "2022-us-senate"}, {"id": "current-senate"}]
        reposition_supplemental_entries(
            entries,
            SUPPLEMENTAL_LEGACY_ELECTIONS,
            parliaments={"us_senate"},
        )
        assert _ids(entries) == ["current-senate", anchor, "2022-us-senate"]

    def test_insert_after_anchor(self) -> None:
        # 2019-general-changed-boundaries is configured to sit just after 2024-general.
        anchor = _supplemental("2019-general-changed-boundaries")["insertAfterId"]
        entries = [
            {"id": "2019-general-changed-boundaries"},
            {"id": anchor},
            {"id": "2019-general"},
        ]
        # parliaments=None processes every supplemental (the None default path).
        reposition_supplemental_entries(entries, SUPPLEMENTAL_LEGACY_ELECTIONS)
        assert _ids(entries) == [anchor, "2019-general-changed-boundaries", "2019-general"]

    def test_parliament_filter_skips_other_pages_supplementals(self) -> None:
        # current-senate belongs to us_senate; a westminster-only page must leave it untouched.
        entries = [{"id": "2024-us-senate"}, {"id": "current-senate"}]
        reposition_supplemental_entries(
            entries,
            SUPPLEMENTAL_LEGACY_ELECTIONS,
            parliaments={"westminster"},
        )
        assert _ids(entries) == ["2024-us-senate", "current-senate"]

    def test_westminster_supplemental_skipped_on_us_page(self) -> None:
        # 2019-general-changed-boundaries defaults to the westminster parliament, so a US-only
        # page skips it (exercises the `get("parliament", "westminster")` default).
        entries = [
            {"id": "2019-general-changed-boundaries"},
            {"id": "2024-general"},
        ]
        reposition_supplemental_entries(
            entries,
            SUPPLEMENTAL_LEGACY_ELECTIONS,
            parliaments={"us_senate"},
        )
        assert _ids(entries) == ["2019-general-changed-boundaries", "2024-general"]

    def test_missing_entry_is_a_noop(self) -> None:
        # No supplemental ids present → nothing to reposition, no error.
        entries = [{"id": "2024-general"}, {"id": "2019-general"}]
        reposition_supplemental_entries(entries, SUPPLEMENTAL_LEGACY_ELECTIONS)
        assert _ids(entries) == ["2024-general", "2019-general"]

    def test_is_idempotent(self) -> None:
        anchor = _supplemental("current-senate")["insertBeforeId"]
        entries = [{"id": anchor}, {"id": "current-senate"}]
        reposition_supplemental_entries(
            entries,
            SUPPLEMENTAL_LEGACY_ELECTIONS,
            parliaments={"us_senate"},
        )
        once = _ids(entries)
        reposition_supplemental_entries(
            entries,
            SUPPLEMENTAL_LEGACY_ELECTIONS,
            parliaments={"us_senate"},
        )
        assert _ids(entries) == once == ["current-senate", anchor]


class TestApplySupplementalPrebuilt:
    """The prebuilt branch (Current Senate): registration must require the result file.

    Prebuilt supplementals have their result file generated by a separate converter; the
    export only registers the manifest entry. A missing file used to warn and register a
    dangling ``results/`` reference — it must raise instead.
    """

    def _apply(
        self,
        manifest_entries: list[dict[str, Any]],
        results_dir: Path,
        legacy_files_dir: Path,
        *,
        dry_run: bool = False,
    ) -> tuple[dict[str, str], dict[str, str]]:
        map_files_by_id: dict[str, str] = {}
        data_files_by_election_id: dict[str, str] = {}
        apply_supplemental_legacy_elections(
            manifest_entries,
            map_files_by_id,
            data_files_by_election_id,
            results_dir,
            legacy_files_dir,
            dry_run,
            parliaments={"us_senate"},
        )
        return map_files_by_id, data_files_by_election_id

    def test_missing_prebuilt_result_file_raises(self, tmp_path: Path) -> None:
        entries: list[dict[str, Any]] = []
        with pytest.raises(FileNotFoundError, match="senate-current.json"):
            self._apply(entries, tmp_path / "results", tmp_path)
        # Nothing may be registered for the broken supplemental.
        assert entries == []

    def test_present_prebuilt_result_file_registers_entry_with_flags(self, tmp_path: Path) -> None:
        results_dir = tmp_path / "results"
        results_dir.mkdir()
        (results_dir / "senate-current.json").write_text("{}", encoding="utf-8")

        entries: list[dict[str, Any]] = []
        map_files, data_files = self._apply(entries, results_dir, tmp_path)

        (entry,) = entries
        assert entry["id"] == "current-senate"
        assert entry["mapId"] == 23
        assert entry["parliament"] == "us_senate"
        # These flags drive the member-tally subtitle and the "next up" cycle filter.
        assert entry["multiMember"] is True
        assert entry["upcomingElections"] is True
        assert data_files["current-senate"] == "results/senate-current.json"
        assert map_files["23"] == "maps/map-23.topo.json"

    def test_dry_run_still_requires_prebuilt_result_file(self, tmp_path: Path) -> None:
        # Consistent with the missing-sourceFile error: dry-run validates inputs too.
        with pytest.raises(FileNotFoundError):
            self._apply([], tmp_path / "results", tmp_path, dry_run=True)


@pytest.fixture()
def uk_supplemental(monkeypatch: pytest.MonkeyPatch) -> dict[str, Any]:
    """Isolate supplemental configuration from repository election files."""
    supplemental: dict[str, Any] = {
        "id": "synthetic-uk",
        "name": "Synthetic UK boundaries",
        "type": "uk_general",
        "mapId": 42,
        "sourceFile": "synthetic-source.json",
        "resultFile": "synthetic-result.json",
        "insertAfterId": "anchor",
    }
    other_parliament: dict[str, Any] = {
        "id": "synthetic-senate",
        "name": "Synthetic Senate",
        "type": "us_senate",
        "mapId": 99,
        "parliament": "us_senate",
        "resultFile": "missing-senate.json",
        "prebuilt": True,
    }
    monkeypatch.setattr(
        legacy, "SUPPLEMENTAL_LEGACY_ELECTIONS", [supplemental, other_parliament],
    )
    return supplemental


_LEGACY_UK_PAYLOAD: dict[str, Any] = {
    "Zulu": {
        "seatInfo": {"region": "North-East", "current": "Labour"},
        "partyInfo": {
            "conservative": {"total": 25},
            "labour": {"total": 75},
            "green": {"total": 0},
        },
    },
    "Alpha": {
        "seatInfo": {"region": "South West", "current": "Conservative"},
        "partyInfo": {"conservative": {"total": 60.5}, "labour": {"total": 39}},
    },
}
_UK_PARTIES: list[dict[str, Any]] = [
    {"key": "labour", "id": 17},
    {"key": "conservative", "id": 29},
    {"key": "green", "id": 31},
]
_UK_REGIONS: dict[str, list[dict[str, Any]]] = {
    "42": [{"name": "North East", "id": 73}, {"name": "South-West", "id": 84}],
    "99": [{"name": "North East", "id": 999}],
}
_UK_ENTRY: dict[str, Any] = {
    "id": "synthetic-uk",
    "name": "Synthetic UK boundaries",
    "type": "uk_general",
    "mapId": 42,
    "parliament": "westminster",
}


def _write_uk_source(tmp_path: Path, payload: dict[str, Any]) -> Path:
    source = tmp_path / "legacy" / "synthetic-source.json"
    source.parent.mkdir()
    source.write_text(json.dumps(payload), encoding="utf-8")
    return source


def _apply_uk(
    tmp_path: Path,
    entries: list[dict[str, Any]],
    *,
    maps: dict[str, str] | None = None,
    data: dict[str, str] | None = None,
    dry_run: bool = False,
    parties: list[dict[str, Any]] | None = None,
    regions: dict[str, list[dict[str, Any]]] | None = None,
    parliaments: set[str] | None = None,
) -> tuple[dict[str, str], dict[str, str]]:
    maps = {} if maps is None else maps
    data = {} if data is None else data
    apply_supplemental_legacy_elections(
        entries, maps, data, tmp_path / "results", tmp_path / "legacy", dry_run,
        manifest_parties=parties,
        manifest_regions_by_map_id=regions,
        parliaments={"westminster"} if parliaments is None else parliaments,
    )
    return maps, data


@pytest.mark.parametrize("missing_source_name", [False, True])
@pytest.mark.parametrize("dry_run", [False, True])
def test_uk_missing_source_fails_before_manifest_registration(
    tmp_path: Path, uk_supplemental: dict[str, Any], missing_source_name: bool,
    dry_run: bool,
) -> None:
    if missing_source_name:
        del uk_supplemental["sourceFile"]
    anchor = {"id": "anchor", "parliament": "westminster"}
    entries = [anchor]
    maps = {"7": "maps/unrelated.json"}
    data = {"other": "results/unrelated.json"}
    error = ValueError if missing_source_name else FileNotFoundError
    message = (
        "define a 'sourceFile'" if missing_source_name else "synthetic-source.json"
    )
    with pytest.raises(error, match=message):
        _apply_uk(tmp_path, entries, maps=maps, data=data, dry_run=dry_run)
    assert entries == [anchor]
    # Reference planning precedes source validation, even when validation fails.
    assert maps == {"7": "maps/unrelated.json", "42": "maps/map-42.topo.json"}
    assert data == {
        "other": "results/unrelated.json",
        "synthetic-uk": "results/synthetic-result.json",
    }
    assert not (tmp_path / "results").exists()


def test_uk_legacy_conversion_uses_parties_and_map_scoped_regions(
    tmp_path: Path, uk_supplemental: dict[str, Any],
) -> None:
    source = _write_uk_source(tmp_path, _LEGACY_UK_PAYLOAD)
    original = source.read_bytes()
    entries: list[dict[str, Any]] = []
    maps, data = _apply_uk(
        tmp_path, entries, parties=_UK_PARTIES, regions=_UK_REGIONS,
    )
    assert json.loads((tmp_path / "results/synthetic-result.json").read_text()) == {
        "schema": "pf-results-v4",
        "seats": [
            {"n": "Alpha", "r": 84, "w": 29, "p": [[29, 60.5], [17, 39]]},
            {"n": "Zulu", "r": 73, "w": 17, "p": [[17, 75], [29, 25]]},
        ],
    }
    assert entries == [_UK_ENTRY]
    assert maps == {"42": "maps/map-42.topo.json"}
    assert data == {"synthetic-uk": "results/synthetic-result.json"}
    assert source.read_bytes() == original


@pytest.mark.parametrize(
    "mode",
    ["schema", "no-parties", "empty-parties", "no-regions", "empty-regions"],
)
def test_uk_raw_payload_passthrough(
    tmp_path: Path, uk_supplemental: dict[str, Any], mode: str,
) -> None:
    payload = (
        {"schema": "pf-results-v4", "seats": [{"n": "Raw", "p": [[17, 5]]}]}
        if mode == "schema" else _LEGACY_UK_PAYLOAD
    )
    _write_uk_source(tmp_path, payload)
    parties = (
        None if mode == "no-parties" else [] if mode == "empty-parties"
        else _UK_PARTIES
    )
    regions = (
        None if mode == "no-regions" else {} if mode == "empty-regions"
        else _UK_REGIONS
    )
    entries: list[dict[str, Any]] = []
    _apply_uk(tmp_path, entries, parties=parties, regions=regions)
    result = tmp_path / "results/synthetic-result.json"
    assert json.loads(result.read_text()) == payload
    assert entries == [_UK_ENTRY]


@pytest.mark.parametrize("position, anchor_exists", [
    ("insertAfterId", True), ("insertAfterId", False),
    ("insertBeforeId", True), ("insertBeforeId", False), ("none", False),
])
def test_uk_manifest_insertion_and_existing_reference_preservation(
    tmp_path: Path, uk_supplemental: dict[str, Any], position: str, anchor_exists: bool,
) -> None:
    uk_supplemental.pop("insertAfterId")
    if position != "none":
        uk_supplemental[position] = "anchor"
    _write_uk_source(tmp_path, _LEGACY_UK_PAYLOAD)
    first = {"id": "first", "parliament": "holyrood", "custom": 123}
    anchor = {"id": "anchor", "parliament": "westminster"}
    last = {"id": "last", "parliament": "us_senate"}
    entries: list[dict[str, Any]] = (
        [first, anchor, last] if anchor_exists else [first, last]
    )
    maps = {"42": "maps/custom-uk.json", "99": "maps/senate.json"}
    data = {"last": "results/unrelated.json"}
    sentinel = tmp_path / "results/unrelated.json"
    sentinel.parent.mkdir()
    sentinel.write_bytes(b"unchanged foreign results")
    returned_maps, returned_data = _apply_uk(tmp_path, entries, maps=maps, data=data)
    expected = (
        [first, anchor, _UK_ENTRY, last] if position == "insertAfterId"
        else [first, _UK_ENTRY, anchor, last]
    ) if anchor_exists else [first, last, _UK_ENTRY]
    assert entries == expected
    assert returned_maps is maps and returned_data is data
    assert maps == {"42": "maps/custom-uk.json", "99": "maps/senate.json"}
    assert data == {
        "last": "results/unrelated.json",
        "synthetic-uk": "results/synthetic-result.json",
    }
    assert sentinel.read_bytes() == b"unchanged foreign results"
    assert not (tmp_path / "results/missing-senate.json").exists()


def test_uk_existing_entry_replaced_in_place_with_flags(
    tmp_path: Path, uk_supplemental: dict[str, Any],
) -> None:
    uk_supplemental.update({"multiMember": True, "upcomingElections": True})
    _write_uk_source(tmp_path, _LEGACY_UK_PAYLOAD)
    first = {"id": "first", "parliament": "holyrood"}
    stale = {"id": "synthetic-uk", "name": "Outdated", "obsolete": True}
    anchor = {"id": "anchor", "parliament": "westminster"}
    entries: list[dict[str, Any]] = [first, stale, anchor]
    _apply_uk(tmp_path, entries)
    expected = {**_UK_ENTRY, "multiMember": True, "upcomingElections": True}
    assert entries == [first, expected, anchor]
    assert entries[0] is first and entries[2] is anchor


def test_uk_dry_run_plans_references_without_reading_or_writing_json(
    tmp_path: Path, uk_supplemental: dict[str, Any],
    capsys: pytest.CaptureFixture[str],
) -> None:
    source = _write_uk_source(tmp_path, {})
    source.write_text("invalid JSON is not parsed in a dry run", encoding="utf-8")
    result = tmp_path / "results/synthetic-result.json"
    result.parent.mkdir()
    result.write_bytes(b"previous result remains untouched")
    before = {
        p.relative_to(tmp_path): p.read_bytes()
        for p in tmp_path.rglob("*") if p.is_file()
    }
    entries: list[dict[str, Any]] = [{"id": "anchor"}]
    maps, data = _apply_uk(
        tmp_path, entries, dry_run=True, parties=_UK_PARTIES, regions=_UK_REGIONS,
    )
    assert entries == [{"id": "anchor"}, _UK_ENTRY]
    assert maps == {"42": "maps/map-42.topo.json"}
    assert data == {"synthetic-uk": "results/synthetic-result.json"}
    after = {
        p.relative_to(tmp_path): p.read_bytes()
        for p in tmp_path.rglob("*") if p.is_file()
    }
    assert after == before
    output = capsys.readouterr().out
    assert "Would write supplemental results" in output
    assert "synthetic-result.json" in output and "synthetic-source.json" in output


def test_uk_parliament_filter_skips_source_validation_and_all_changes(
    tmp_path: Path, uk_supplemental: dict[str, Any],
) -> None:
    entries = [{"id": "existing", "parliament": "holyrood"}]
    maps = {"8": "maps/holyrood.json"}
    data = {"existing": "results/holyrood.json"}
    _apply_uk(tmp_path, entries, maps=maps, data=data, parliaments={"holyrood"})
    assert entries == [{"id": "existing", "parliament": "holyrood"}]
    assert maps == {"8": "maps/holyrood.json"}
    assert data == {"existing": "results/holyrood.json"}
    assert not (tmp_path / "results").exists()
