"""Tests for scripts.export.legacy — supplemental-entry repositioning.

``reposition_supplemental_entries`` re-applies each supplemental's configured
``insertBeforeId`` / ``insertAfterId`` after ``reorder_manifest_entries`` (which sorts by the
previous manifest order) may have moved it. It also honours the per-page ``parliaments`` filter
so a page only repositions its own supplementals. Pure function operating on a list of dicts.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

import pytest

from scripts.export.legacy import (
    SUPPLEMENTAL_LEGACY_ELECTIONS,
    apply_supplemental_legacy_elections,
    reposition_supplemental_entries,
)


def _supplemental(sid: str) -> dict[str, Any]:
    """The configured supplemental with id ``sid`` (so anchors track the source of truth)."""
    return next(s for s in SUPPLEMENTAL_LEGACY_ELECTIONS if s["id"] == sid)


def _ids(entries: list[dict[str, Any]]) -> list[str]:
    return [e["id"] for e in entries]


class TestRepositionSupplementalEntries:
    def test_insert_before_anchor(self) -> None:
        # current-senate is configured to lead its class (insertBeforeId=2024-us-senate); a prior
        # reorder can push it to the end, so it must be pulled back in front of the anchor.
        anchor = _supplemental("current-senate")["insertBeforeId"]
        entries = [{"id": anchor}, {"id": "2022-us-senate"}, {"id": "current-senate"}]
        reposition_supplemental_entries(entries, parliaments={"us_senate"})
        assert _ids(entries) == ["current-senate", anchor, "2022-us-senate"]

    def test_insert_after_anchor(self) -> None:
        # 2019-general-changed-boundaries is configured to sit just after 2024-general.
        anchor = _supplemental("2019-general-changed-boundaries")["insertAfterId"]
        entries = [
            {"id": "2019-general-changed-boundaries"},
            {"id": anchor},
            {"id": "2019-general"},
        ]
        # parliaments=None processes every supplemental (the None default path).
        reposition_supplemental_entries(entries, None)
        assert _ids(entries) == [anchor, "2019-general-changed-boundaries", "2019-general"]

    def test_parliament_filter_skips_other_pages_supplementals(self) -> None:
        # current-senate belongs to us_senate; a westminster-only page must leave it untouched.
        entries = [{"id": "2024-us-senate"}, {"id": "current-senate"}]
        reposition_supplemental_entries(entries, parliaments={"westminster"})
        assert _ids(entries) == ["2024-us-senate", "current-senate"]

    def test_westminster_supplemental_skipped_on_us_page(self) -> None:
        # 2019-general-changed-boundaries defaults to the westminster parliament, so a US-only
        # page skips it (exercises the `get("parliament", "westminster")` default).
        entries = [
            {"id": "2019-general-changed-boundaries"},
            {"id": "2024-general"},
        ]
        reposition_supplemental_entries(entries, parliaments={"us_senate"})
        assert _ids(entries) == ["2019-general-changed-boundaries", "2024-general"]

    def test_missing_entry_is_a_noop(self) -> None:
        # No supplemental ids present → nothing to reposition, no error.
        entries = [{"id": "2024-general"}, {"id": "2019-general"}]
        reposition_supplemental_entries(entries, None)
        assert _ids(entries) == ["2024-general", "2019-general"]

    def test_is_idempotent(self) -> None:
        anchor = _supplemental("current-senate")["insertBeforeId"]
        entries = [{"id": anchor}, {"id": "current-senate"}]
        reposition_supplemental_entries(entries, parliaments={"us_senate"})
        once = _ids(entries)
        reposition_supplemental_entries(entries, parliaments={"us_senate"})
        assert _ids(entries) == once == ["current-senate", anchor]


class TestApplySupplementalPrebuilt:
    """The prebuilt branch (Current Senate): registration must require the result file.

    Prebuilt supplementals have their result file generated by a separate converter; the
    export only registers the manifest entry. A missing file used to warn and register a
    dangling ``results/`` reference — it must raise instead.
    """

    def _apply(
        self,
        manifest_entries: list[dict[str, Any]],
        results_dir: Path,
        legacy_files_dir: Path,
        *,
        dry_run: bool = False,
    ) -> tuple[dict[str, str], dict[str, str]]:
        map_files_by_id: dict[str, str] = {}
        data_files_by_election_id: dict[str, str] = {}
        apply_supplemental_legacy_elections(
            manifest_entries,
            map_files_by_id,
            data_files_by_election_id,
            results_dir,
            legacy_files_dir,
            dry_run,
            parliaments={"us_senate"},
        )
        return map_files_by_id, data_files_by_election_id

    def test_missing_prebuilt_result_file_raises(self, tmp_path: Path) -> None:
        entries: list[dict[str, Any]] = []
        with pytest.raises(FileNotFoundError, match="senate-current.json"):
            self._apply(entries, tmp_path / "results", tmp_path)
        # Nothing may be registered for the broken supplemental.
        assert entries == []

    def test_present_prebuilt_result_file_registers_entry_with_flags(self, tmp_path: Path) -> None:
        results_dir = tmp_path / "results"
        results_dir.mkdir()
        (results_dir / "senate-current.json").write_text("{}", encoding="utf-8")

        entries: list[dict[str, Any]] = []
        map_files, data_files = self._apply(entries, results_dir, tmp_path)

        (entry,) = entries
        assert entry["id"] == "current-senate"
        assert entry["mapId"] == 23
        assert entry["parliament"] == "us_senate"
        # These flags drive the member-tally subtitle and the "next up" cycle filter.
        assert entry["multiMember"] is True
        assert entry["upcomingElections"] is True
        assert data_files["current-senate"] == "results/senate-current.json"
        assert map_files["23"] == "maps/map-23.topo.json"

    def test_dry_run_still_requires_prebuilt_result_file(self, tmp_path: Path) -> None:
        # Consistent with the missing-sourceFile error: dry-run validates inputs too.
        with pytest.raises(FileNotFoundError):
            self._apply([], tmp_path / "results", tmp_path, dry_run=True)
